# Generated by Django 3.1.2 on 2020-10-16 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_name', models.CharField(max_length=25)),
                ('command_info', models.CharField(max_length=200)),
                ('command_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.category')),
            ],
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_usage', models.CharField(max_length=25)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.command')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_option', models.CharField(max_length=25)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.command')),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_example', models.CharField(max_length=200)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.command')),
            ],
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_alias', models.CharField(max_length=25)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.command')),
            ],
        ),
    ]
